/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms    @Override
    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Insets getBorderInsets(Component c) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean isBorderOpaque() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
/JFrame.java to edit this template
 */
package UI;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class ChucNang extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    /**Khởi tạo biến image cho giao diện chức năng**/private final ImageIcon img_Sach,img_TaiKhoan,img_NhanVien,img_KhachHang,img_DoanhThu,img_HoaDon,img_LichSu,img_DangXuat;
    private final String role=DangNhap.Role;
    private final String username=DangNhap.Username;
    private static final Logger logger = Setting.SettingUI.logger;
    public ChucNang() {
        img_Sach=new ImageIcon(new ImageIcon(getClass().getResource("/Image/bookicon.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
        img_TaiKhoan=new ImageIcon(new ImageIcon(getClass().getResource("/Image/accounticon.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
        img_NhanVien=new ImageIcon(new ImageIcon(getClass().getResource("/Image/nhanvienicon.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
        img_KhachHang=new ImageIcon(new ImageIcon(getClass().getResource("/Image/khachhangicon.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
        img_DoanhThu=new ImageIcon(new ImageIcon(getClass().getResource("/Image/doanhthuicon.png")).getImage().getScaledInstance(200, 140, Image.SCALE_SMOOTH));
        img_HoaDon=new ImageIcon(new ImageIcon(getClass().getResource("/Image/hoadonicon.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
        img_LichSu=new ImageIcon(new ImageIcon(getClass().getResource("/Image/lichsuicon.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
        img_DangXuat=new ImageIcon(new ImageIcon(getClass().getResource("/Image/dangxuaticon.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
        initComponents();
        jlabel_hello.setText("Xin chào "+username+",");
        setRole(role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_ChucNang_main = new javax.swing.JPanel();
        btn_QuanLyTaiKhoan = Setting.SettingUI.createRoundedButton(0.5,0.5,70);
        btn_QuanLySach = Setting.SettingUI.createRoundedButton(0.5,0.5,70);
        btn_QuanLyNhanVien = Setting.SettingUI.createRoundedButton(0.5,0.5,70);
        btn_QuanLyKhachHang = Setting.SettingUI.createRoundedButton(0.5,0.5,70);
        btn_DangXuat = Setting.SettingUI.createRoundedButton(0.5,0.5,70);
        btn_QuanLyLichSu = Setting.SettingUI.createRoundedButton(0.5,0.5,70);
        btn_QuanLyHoaDon = Setting.SettingUI.createRoundedButton(0.5,0.5,70);
        btn_QuanLyDoanhThu = Setting.SettingUI.createRoundedButton(0.5,0.5,70);
        jLabel_Sach_title = new javax.swing.JLabel();
        jLabel_TaiKhoan_title = new javax.swing.JLabel();
        jLabel_NhanVien_title = new javax.swing.JLabel();
        jLabel_KhachHang_title = new javax.swing.JLabel();
        jLabel_DoanhThu_title = new javax.swing.JLabel();
        jLabel_HoaDon_tittle = new javax.swing.JLabel();
        jLabel_LichSu_title = new javax.swing.JLabel();
        jLabel_DangXuat_title = new javax.swing.JLabel();
        jlabel_hello = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(600, 300));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1292, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1063, 600));
        setResizable(false);

        jPanel_ChucNang_main.setBackground(Setting.SettingUI.UI_colorDefault);
        jPanel_ChucNang_main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_ChucNang_main.setToolTipText("");
        jPanel_ChucNang_main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_ChucNang_main.setPreferredSize(new java.awt.Dimension(1063, 600));

        btn_QuanLyTaiKhoan.setBackground(Setting.SettingUI.btn_colorDefault);
        btn_QuanLyTaiKhoan.setIcon(img_TaiKhoan);
        btn_QuanLyTaiKhoan.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btn_QuanLyTaiKhoan.setBorderPainted(false);
        btn_QuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyTaiKhoanActionPerformed(evt);
            }
        });

        btn_QuanLySach.setBackground(Setting.SettingUI.btn_colorDefault);
        btn_QuanLySach.setIcon(img_Sach);
        btn_QuanLySach.setBorder(null);
        btn_QuanLySach.setBorderPainted(false);
        btn_QuanLySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLySachActionPerformed(evt);
            }
        });

        btn_QuanLyNhanVien.setBackground(Setting.SettingUI.btn_colorDefault);
        btn_QuanLyNhanVien.setIcon(img_NhanVien);
        btn_QuanLyNhanVien.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btn_QuanLyNhanVien.setBorderPainted(false);
        btn_QuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyNhanVienActionPerformed(evt);
            }
        });

        btn_QuanLyKhachHang.setBackground(Setting.SettingUI.btn_colorDefault);
        btn_QuanLyKhachHang.setIcon(img_KhachHang);
        btn_QuanLyKhachHang.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btn_QuanLyKhachHang.setBorderPainted(false);
        btn_QuanLyKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyKhachHangActionPerformed(evt);
            }
        });

        btn_DangXuat.setBackground(Setting.SettingUI.btn_colorDefault);
        btn_DangXuat.setIcon(img_DangXuat);
        btn_DangXuat.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btn_DangXuat.setBorderPainted(false);
        btn_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuatActionPerformed(evt);
            }
        });

        btn_QuanLyLichSu.setBackground(Setting.SettingUI.btn_colorDefault);
        btn_QuanLyLichSu.setIcon(img_LichSu);
        btn_QuanLyLichSu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btn_QuanLyLichSu.setBorderPainted(false);
        btn_QuanLyLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyLichSuActionPerformed(evt);
            }
        });

        btn_QuanLyHoaDon.setBackground(Setting.SettingUI.btn_colorDefault);
        btn_QuanLyHoaDon.setIcon(img_HoaDon);
        btn_QuanLyHoaDon.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btn_QuanLyHoaDon.setBorderPainted(false);
        btn_QuanLyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyHoaDonActionPerformed(evt);
            }
        });

        btn_QuanLyDoanhThu.setBackground(Setting.SettingUI.btn_colorDefault);
        btn_QuanLyDoanhThu.setIcon(img_DoanhThu);
        btn_QuanLyDoanhThu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btn_QuanLyDoanhThu.setBorderPainted(false);
        btn_QuanLyDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyDoanhThuActionPerformed(evt);
            }
        });

        jLabel_Sach_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Sach_title.setText("Sách");

        jLabel_TaiKhoan_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_TaiKhoan_title.setText("Tài Khoản");

        jLabel_NhanVien_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_NhanVien_title.setText("Nhân Viên");

        jLabel_KhachHang_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_KhachHang_title.setText("Khách Hàng");

        jLabel_DoanhThu_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_DoanhThu_title.setText("Doanh Thu");

        jLabel_HoaDon_tittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_HoaDon_tittle.setText("Hóa Đơn");

        jLabel_LichSu_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_LichSu_title.setText("Lịch Sử");

        jLabel_DangXuat_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_DangXuat_title.setText("Đăng Xuất");

        jlabel_hello.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabel_hello.setText("jLabel1");

        javax.swing.GroupLayout jPanel_ChucNang_mainLayout = new javax.swing.GroupLayout(jPanel_ChucNang_main);
        jPanel_ChucNang_main.setLayout(jPanel_ChucNang_mainLayout);
        jPanel_ChucNang_mainLayout.setHorizontalGroup(
            jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_QuanLyDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_QuanLySach, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                                .addComponent(btn_QuanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(btn_QuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                                .addComponent(btn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_QuanLyLichSu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel_Sach_title)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel_TaiKhoan_title)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel_NhanVien_title)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel_KhachHang_title))
                    .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel_DoanhThu_title)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel_HoaDon_tittle)
                        .addGap(155, 155, 155)
                        .addComponent(jLabel_LichSu_title, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel_DangXuat_title, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jlabel_hello, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel_ChucNang_mainLayout.setVerticalGroup(
            jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel_hello)
                .addGap(29, 29, 29)
                .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_QuanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QuanLySach, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Sach_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_TaiKhoan_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_NhanVien_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_KhachHang_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_QuanLyDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_QuanLyLichSu, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DoanhThu_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_HoaDon_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_LichSu_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_DangXuat_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ChucNang_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ChucNang_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1063, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyTaiKhoanActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng Qu\u1ea3n L\u00fd T\u00e0i Kho\u1ea3n\n", username);
        this.setVisible(false);
        new QuanLyTaiKhoan().setVisible(true);  
    }//GEN-LAST:event_btn_QuanLyTaiKhoanActionPerformed

    private void btn_QuanLySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLySachActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng Qu\u1ea3n L\u00fd S\u00e1ch\n", username);
        this.setVisible(false);
        new QuanLySach().setVisible(true);
    }//GEN-LAST:event_btn_QuanLySachActionPerformed

    private void btn_QuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyNhanVienActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng Qu\u1ea3n L\u00fd Nh\u00e2n Vi\u00ean\n", username);
        this.setVisible(false);
        new QuanLyNhanVien().setVisible(true);
    }//GEN-LAST:event_btn_QuanLyNhanVienActionPerformed

    private void btn_QuanLyKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyKhachHangActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng Qu\u1ea3n L\u00fd Kh\u00e1ch H\u00e0ng\n", username);
        this.setVisible(false);
        new QuanLyKhachHang().setVisible(true);
    }//GEN-LAST:event_btn_QuanLyKhachHangActionPerformed

    private void btn_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuatActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 \u0111\u0103ng xu\u1ea5t\n", username);
        this.setVisible(false);
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_btn_DangXuatActionPerformed

    private void btn_QuanLyLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyLichSuActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng Qu\u1ea3n L\u00fd L\u1ecbch S\u1eed Thao T\u00e1c\n", username);
        this.setVisible(false);
        new LichSu().setVisible(true);
    }//GEN-LAST:event_btn_QuanLyLichSuActionPerformed

    private void btn_QuanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyHoaDonActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng Qu\u1ea3n L\u00fd H\u00f3a \u0110\u01a1n\n", username);
        this.setVisible(false);
        new QuanLyHoaDon().setVisible(true);
    }//GEN-LAST:event_btn_QuanLyHoaDonActionPerformed

    private void btn_QuanLyDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyDoanhThuActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng Qu\u1ea3n L\u00fd Doanh Thu\n", username);
        this.setVisible(false);
        new QuanLyDoanhThu().setVisible(true);
    }//GEN-LAST:event_btn_QuanLyDoanhThuActionPerformed
    private void setRole(String Role){
        switch (Role) {
            case "Nhân Viên" -> {
                btn_QuanLyTaiKhoan.setEnabled(false);
                btn_QuanLyNhanVien.setEnabled(false);
                btn_QuanLyDoanhThu.setEnabled(false);
            }
            case "Quản Lý" -> {
            }
            case "Khách Hàng" -> {
                btn_QuanLyTaiKhoan.setEnabled(false);
                btn_QuanLyNhanVien.setEnabled(false);
                btn_QuanLyDoanhThu.setEnabled(false);
                btn_QuanLyLichSu.setEnabled(false);
                btn_QuanLyHoaDon.setEnabled(false);
                btn_QuanLyKhachHang.setEnabled(false);
            }
            default -> {
            }
        }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ChucNang().setVisible(true);
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangXuat;
    private javax.swing.JButton btn_QuanLyDoanhThu;
    private javax.swing.JButton btn_QuanLyHoaDon;
    private javax.swing.JButton btn_QuanLyKhachHang;
    private javax.swing.JButton btn_QuanLyLichSu;
    private javax.swing.JButton btn_QuanLyNhanVien;
    private javax.swing.JButton btn_QuanLySach;
    private javax.swing.JButton btn_QuanLyTaiKhoan;
    private javax.swing.JLabel jLabel_DangXuat_title;
    private javax.swing.JLabel jLabel_DoanhThu_title;
    private javax.swing.JLabel jLabel_HoaDon_tittle;
    private javax.swing.JLabel jLabel_KhachHang_title;
    private javax.swing.JLabel jLabel_LichSu_title;
    private javax.swing.JLabel jLabel_NhanVien_title;
    private javax.swing.JLabel jLabel_Sach_title;
    private javax.swing.JLabel jLabel_TaiKhoan_title;
    private javax.swing.JPanel jPanel_ChucNang_main;
    private javax.swing.JLabel jlabel_hello;
    // End of variables declaration//GEN-END:variables
}
