/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms    @Override
    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Insets getBorderInsets(Component c) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean isBorderOpaque() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
/JFrame.java to edit this template
 */
package UI;


import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import DB.DbQuery;
import java.net.MalformedURLException;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Admin
 */
public class QuanLyNhanVien extends javax.swing.JFrame{

    /**
     * Creates new form DangNhap
     */
    private final ImageIcon img_Back;
    private final String role=DangNhap.Role;
    private DefaultTableModel tbModel;
    private final int image_Width=218;
    private final DbQuery dbqr=new DbQuery();
    private ResultSet rs;
    private String dialog_Opened="";
    private final String username=DangNhap.Username;
    private static final Logger logger = Setting.SettingUI.logger;

    public QuanLyNhanVien() {
        img_Back=new ImageIcon(new ImageIcon(getClass().getResource("/Image/backicon.png")).getImage().getScaledInstance(45, 25, Image.SCALE_SMOOTH));
        initComponents();
        setRole(role);
        load_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_TimKiem_dialog = new javax.swing.JFrame();
        jPanel_TimKiemBox = new javax.swing.JPanel();
        jTextField_TimKiemBox_searchString = new javax.swing.JTextField();
        btn_TimKiemBox_search = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_TimKiemBox_close = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        jComboBox_TimKiemBox_item = new javax.swing.JComboBox<>();
        jFrame_ChiTiet_dialog = new javax.swing.JFrame();
        jPanel_ChiTietBox = new javax.swing.JPanel();
        btn_ChiTietBox_close = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        jPanel_ChiTietBox_Image = new javax.swing.JPanel();
        jLabel_ChiTietBox_Image = new javax.swing.JLabel();
        jScrollPane_ChiTietBox_Content = new javax.swing.JScrollPane();
        jTextPane_ChiTietBox_ThongTin = new javax.swing.JTextPane();
        jFrame_CapNhatThem_dialog = new javax.swing.JFrame();
        jPanel_CapNhatThemBox = new javax.swing.JPanel();
        btn_CapNhatThemBox_CapNhat = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_CapNhatThemBox_close = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        jTextField_CapNhatThemBox_ID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_CapNhatThemBox_Username = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_CapNhatThemBox_HoTen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_CapNhatThemBox_SDT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_CapNhatThemBox_DiaChi = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_CapNhatThemBox_Tuoi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_CapNhatThemBox_QueQuan = new javax.swing.JTextField();
        btn_CapNhatThemBox_Them = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        jComboBox_CapNhatThemBox_GioiTinh = new javax.swing.JComboBox<>();
        jPanel_ChucNang_main = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_TimKiem = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_Them = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_ChiTiet = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_Xoa = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_CapNhat = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        jLabel_mainTittle = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        jFrame_TimKiem_dialog.setLocation(Setting.SettingUI.dialog_Location);
        jFrame_TimKiem_dialog.setMinimumSize(new java.awt.Dimension(466, 143));
        jFrame_TimKiem_dialog.setUndecorated(true);
        jFrame_TimKiem_dialog.setResizable(false);

        jPanel_TimKiemBox.setBackground(new java.awt.Color(255, 138, 20));
        jPanel_TimKiemBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextField_TimKiemBox_searchString.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btn_TimKiemBox_search.setBackground(new java.awt.Color(250, 215, 172));
        btn_TimKiemBox_search.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_TimKiemBox_search.setText("Tìm");
        btn_TimKiemBox_search.setBorderPainted(false);
        btn_TimKiemBox_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemBox_searchActionPerformed(evt);
            }
        });

        btn_TimKiemBox_close.setBackground(new java.awt.Color(250, 215, 172));
        btn_TimKiemBox_close.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_TimKiemBox_close.setText("Đóng");
        btn_TimKiemBox_close.setBorderPainted(false);
        btn_TimKiemBox_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemBox_closeActionPerformed(evt);
            }
        });

        jComboBox_TimKiemBox_item.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_TimKiemBox_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Họ Tên", "Số điện thoại", "Tuổi", "Quê" }));

        javax.swing.GroupLayout jPanel_TimKiemBoxLayout = new javax.swing.GroupLayout(jPanel_TimKiemBox);
        jPanel_TimKiemBox.setLayout(jPanel_TimKiemBoxLayout);
        jPanel_TimKiemBoxLayout.setHorizontalGroup(
            jPanel_TimKiemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TimKiemBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_TimKiemBox_item, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_TimKiemBox_searchString)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TimKiemBoxLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btn_TimKiemBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btn_TimKiemBox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel_TimKiemBoxLayout.setVerticalGroup(
            jPanel_TimKiemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TimKiemBoxLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_TimKiemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_TimKiemBox_searchString, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jComboBox_TimKiemBox_item))
                .addGap(18, 18, 18)
                .addGroup(jPanel_TimKiemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TimKiemBox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiemBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame_TimKiem_dialogLayout = new javax.swing.GroupLayout(jFrame_TimKiem_dialog.getContentPane());
        jFrame_TimKiem_dialog.getContentPane().setLayout(jFrame_TimKiem_dialogLayout);
        jFrame_TimKiem_dialogLayout.setHorizontalGroup(
            jFrame_TimKiem_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_TimKiemBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame_TimKiem_dialogLayout.setVerticalGroup(
            jFrame_TimKiem_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_TimKiemBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame_ChiTiet_dialog.setLocation(Setting.SettingUI.dialog_Location);
        jFrame_ChiTiet_dialog.setMinimumSize(new java.awt.Dimension(466, 345));
        jFrame_ChiTiet_dialog.setUndecorated(true);

        jPanel_ChiTietBox.setBackground(new java.awt.Color(255, 138, 20));
        jPanel_ChiTietBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_ChiTietBox.setPreferredSize(new java.awt.Dimension(466, 623));

        btn_ChiTietBox_close.setBackground(new java.awt.Color(250, 215, 172));
        btn_ChiTietBox_close.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_ChiTietBox_close.setText("Đóng");
        btn_ChiTietBox_close.setBorderPainted(false);
        btn_ChiTietBox_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChiTietBox_closeActionPerformed(evt);
            }
        });

        jPanel_ChiTietBox_Image.setBackground(new java.awt.Color(250, 215, 172));
        jPanel_ChiTietBox_Image.setMaximumSize(new java.awt.Dimension(218, 327));
        jPanel_ChiTietBox_Image.setMinimumSize(new java.awt.Dimension(218, 327));
        jPanel_ChiTietBox_Image.setPreferredSize(new java.awt.Dimension(292, 292));

        jLabel_ChiTietBox_Image.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel_ChiTietBox_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ChiTietBox_Image.setAutoscrolls(true);
        jLabel_ChiTietBox_Image.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_ChiTietBox_Image.setMaximumSize(new java.awt.Dimension(218, 327));
        jLabel_ChiTietBox_Image.setName(""); // NOI18N
        jLabel_ChiTietBox_Image.setPreferredSize(new java.awt.Dimension(218, 327));

        javax.swing.GroupLayout jPanel_ChiTietBox_ImageLayout = new javax.swing.GroupLayout(jPanel_ChiTietBox_Image);
        jPanel_ChiTietBox_Image.setLayout(jPanel_ChiTietBox_ImageLayout);
        jPanel_ChiTietBox_ImageLayout.setHorizontalGroup(
            jPanel_ChiTietBox_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_ChiTietBox_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel_ChiTietBox_ImageLayout.setVerticalGroup(
            jPanel_ChiTietBox_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChiTietBox_ImageLayout.createSequentialGroup()
                .addComponent(jLabel_ChiTietBox_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextPane_ChiTietBox_ThongTin.setEditable(false);
        // Disable auto-scrolling
        DefaultCaret caret1 = (DefaultCaret) jTextPane_ChiTietBox_ThongTin.getCaret();
        caret1.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        jTextPane_ChiTietBox_ThongTin.setBackground(new java.awt.Color(250, 215, 172));
        jTextPane_ChiTietBox_ThongTin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextPane_ChiTietBox_ThongTin.setAutoscrolls(false);
        jTextPane_ChiTietBox_ThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPane_ChiTietBox_ThongTin.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextPane_ChiTietBox_ThongTin.setMaximumSize(new java.awt.Dimension(582, 578));
        jTextPane_ChiTietBox_ThongTin.setName(""); // NOI18N
        jScrollPane_ChiTietBox_Content.setViewportView(jTextPane_ChiTietBox_ThongTin);

        javax.swing.GroupLayout jPanel_ChiTietBoxLayout = new javax.swing.GroupLayout(jPanel_ChiTietBox);
        jPanel_ChiTietBox.setLayout(jPanel_ChiTietBoxLayout);
        jPanel_ChiTietBoxLayout.setHorizontalGroup(
            jPanel_ChiTietBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChiTietBoxLayout.createSequentialGroup()
                .addGroup(jPanel_ChiTietBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ChiTietBoxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_ChiTietBox_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane_ChiTietBox_Content, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_ChiTietBoxLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btn_ChiTietBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel_ChiTietBoxLayout.setVerticalGroup(
            jPanel_ChiTietBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChiTietBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ChiTietBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_ChiTietBox_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane_ChiTietBox_Content))
                .addGap(18, 18, 18)
                .addComponent(btn_ChiTietBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame_ChiTiet_dialogLayout = new javax.swing.GroupLayout(jFrame_ChiTiet_dialog.getContentPane());
        jFrame_ChiTiet_dialog.getContentPane().setLayout(jFrame_ChiTiet_dialogLayout);
        jFrame_ChiTiet_dialogLayout.setHorizontalGroup(
            jFrame_ChiTiet_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ChiTietBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrame_ChiTiet_dialogLayout.setVerticalGroup(
            jFrame_ChiTiet_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ChiTietBox, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jFrame_CapNhatThem_dialog.setLocation(Setting.SettingUI.dialog_Location);
        jFrame_CapNhatThem_dialog.setMinimumSize(new java.awt.Dimension(466, 484));
        jFrame_CapNhatThem_dialog.setUndecorated(true);

        jPanel_CapNhatThemBox.setBackground(new java.awt.Color(255, 138, 20));
        jPanel_CapNhatThemBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_CapNhatThemBox.setMaximumSize(new java.awt.Dimension(466, 623));
        jPanel_CapNhatThemBox.setPreferredSize(new java.awt.Dimension(466, 623));

        btn_CapNhatThemBox_CapNhat.setBackground(new java.awt.Color(250, 215, 172));
        btn_CapNhatThemBox_CapNhat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_CapNhatThemBox_CapNhat.setText("Cập Nhật");
        btn_CapNhatThemBox_CapNhat.setBorderPainted(false);
        btn_CapNhatThemBox_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatThemBox_CapNhatActionPerformed(evt);
            }
        });

        btn_CapNhatThemBox_close.setBackground(new java.awt.Color(250, 215, 172));
        btn_CapNhatThemBox_close.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_CapNhatThemBox_close.setText("Đóng");
        btn_CapNhatThemBox_close.setBorderPainted(false);
        btn_CapNhatThemBox_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatThemBox_closeActionPerformed(evt);
            }
        });

        jTextField_CapNhatThemBox_ID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_CapNhatThemBox_ID.setMaximumSize(new java.awt.Dimension(7, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("ID:");

        jTextField_CapNhatThemBox_Username.setColumns(2);
        jTextField_CapNhatThemBox_Username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_CapNhatThemBox_Username.setActionCommand("<Not Set>");
        jTextField_CapNhatThemBox_Username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_CapNhatThemBox_Username.setMaximumSize(new java.awt.Dimension(7, 35));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Username:");

        jTextField_CapNhatThemBox_HoTen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_CapNhatThemBox_HoTen.setMaximumSize(new java.awt.Dimension(7, 35));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Họ Tên:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("SDT:");

        jTextField_CapNhatThemBox_SDT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_CapNhatThemBox_SDT.setMaximumSize(new java.awt.Dimension(7, 35));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Giới Tính:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Địa Chỉ:");

        jTextField_CapNhatThemBox_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_CapNhatThemBox_DiaChi.setMaximumSize(new java.awt.Dimension(7, 35));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Tuổi:");

        jTextField_CapNhatThemBox_Tuoi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_CapNhatThemBox_Tuoi.setMaximumSize(new java.awt.Dimension(7, 35));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Quê Quán:");

        jTextField_CapNhatThemBox_QueQuan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_CapNhatThemBox_QueQuan.setMaximumSize(new java.awt.Dimension(7, 35));

        btn_CapNhatThemBox_Them.setBackground(new java.awt.Color(250, 215, 172));
        btn_CapNhatThemBox_Them.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_CapNhatThemBox_Them.setText("Thêm");
        btn_CapNhatThemBox_Them.setBorderPainted(false);
        btn_CapNhatThemBox_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatThemBox_ThemActionPerformed(evt);
            }
        });

        jComboBox_CapNhatThemBox_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBox_CapNhatThemBox_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));

        javax.swing.GroupLayout jPanel_CapNhatThemBoxLayout = new javax.swing.GroupLayout(jPanel_CapNhatThemBox);
        jPanel_CapNhatThemBox.setLayout(jPanel_CapNhatThemBoxLayout);
        jPanel_CapNhatThemBoxLayout.setHorizontalGroup(
            jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CapNhatThemBox_QueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CapNhatThemBox_Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CapNhatThemBox_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_CapNhatThemBox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CapNhatThemBox_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CapNhatThemBox_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CapNhatThemBox_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CapNhatThemBox_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_CapNhatThemBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_CapNhatThemBox_CapNhat)
                .addGap(27, 27, 27)
                .addComponent(btn_CapNhatThemBox_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel_CapNhatThemBoxLayout.setVerticalGroup(
            jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_CapNhatThemBox_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_CapNhatThemBox_Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_CapNhatThemBox_HoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_CapNhatThemBox_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_CapNhatThemBox_GioiTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_CapNhatThemBox_DiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_CapNhatThemBox_Tuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_CapNhatThemBox_QueQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CapNhatThemBox_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CapNhatThemBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CapNhatThemBox_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jFrame_CapNhatThem_dialogLayout = new javax.swing.GroupLayout(jFrame_CapNhatThem_dialog.getContentPane());
        jFrame_CapNhatThem_dialog.getContentPane().setLayout(jFrame_CapNhatThem_dialogLayout);
        jFrame_CapNhatThem_dialogLayout.setHorizontalGroup(
            jFrame_CapNhatThem_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_CapNhatThemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrame_CapNhatThem_dialogLayout.setVerticalGroup(
            jFrame_CapNhatThem_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_CapNhatThemBox, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(600, 300));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1063, 623));
        setMinimumSize(new java.awt.Dimension(1063, 623));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1063, 623));
        setResizable(false);

        jPanel_ChucNang_main.setBackground(Setting.SettingUI.UI_colorDefault);
        jPanel_ChucNang_main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_ChucNang_main.setToolTipText("");
        jPanel_ChucNang_main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Họ Tên", "Tác Giả", "Giới Tính", "Tuổi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(30);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(false);
        jTable1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTable1MouseDragged(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_TimKiem.setBackground(new java.awt.Color(250, 215, 172));
        btn_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_TimKiem.setText("Tìm Kiếm");
        btn_TimKiem.setBorderPainted(false);
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_Them.setBackground(new java.awt.Color(250, 215, 172));
        btn_Them.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.setBorderPainted(false);
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_ChiTiet.setBackground(new java.awt.Color(250, 215, 172));
        btn_ChiTiet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ChiTiet.setText("Chi Tiết");
        btn_ChiTiet.setBorderPainted(false);
        btn_ChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChiTietActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(250, 215, 172));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.setBorderPainted(false);
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_CapNhat.setBackground(new java.awt.Color(250, 215, 172));
        btn_CapNhat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_CapNhat.setText("Cập Nhật");
        btn_CapNhat.setBorderPainted(false);
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        jLabel_mainTittle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_mainTittle.setText("Quản Lý Nhân Viên");

        btn_back.setBackground(new java.awt.Color(250, 215, 172));
        btn_back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_back.setIcon(img_Back);
        btn_back.setBorderPainted(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ChucNang_mainLayout = new javax.swing.GroupLayout(jPanel_ChucNang_main);
        jPanel_ChucNang_main.setLayout(jPanel_ChucNang_mainLayout);
        jPanel_ChucNang_mainLayout.setHorizontalGroup(
            jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ChiTiet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_mainTittle)
                .addGap(354, 354, 354))
            .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                    .addGap(892, 892, 892)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(169, Short.MAX_VALUE)))
            .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE))
        );
        jPanel_ChucNang_mainLayout.setVerticalGroup(
            jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_mainTittle)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btn_TimKiem)
                .addGap(28, 28, 28)
                .addComponent(btn_ChiTiet)
                .addGap(28, 28, 28)
                .addComponent(btn_Them)
                .addGap(28, 28, 28)
                .addComponent(btn_CapNhat)
                .addGap(28, 28, 28)
                .addComponent(btn_Xoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChucNang_mainLayout.createSequentialGroup()
                    .addGap(0, 75, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChucNang_mainLayout.createSequentialGroup()
                    .addContainerGap(75, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(542, 542, 542)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ChucNang_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ChucNang_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1063, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

/**
 * Phương thức này thực hiện việc tải dữ liệu từ cơ sở dữ liệu và hiển thị nó trong bảng.
 * Dữ liệu được lấy dựa trên các thông tin nhập từ các thành phần giao diện như combobox và textbox.
 * 
 * @throws SQLException Nếu có lỗi xảy ra trong quá trình truy vấn cơ sở dữ liệu.
 */
    private void load_Table()
    {
        if(tbModel!=null)
            tbModel.setRowCount(0);
        // Lấy thông tin từ các thành phần giao diện
        String typeSearch = convertToDbString(jComboBox_TimKiemBox_item.getItemAt(jComboBox_TimKiemBox_item.getSelectedIndex()));
        String searchString = jTextField_TimKiemBox_searchString.getText();

        try {
            // Kiểm tra loại sắp xếp được chọn từ combobox
                // Trường hợp 1: Sắp xếp theo bảng sách
                // Thực hiện truy vấn cơ sở dữ liệu

                rs = dbqr.ExcuQuery_GetTable("NHANVIEN",
                        typeSearch + " like N'%" + searchString + "%'",
                        "Id ASC");

                // Hiển thị dữ liệu trong bảng
                tbModel = (DefaultTableModel) jTable1.getModel();
                while (rs.next()) {
                    String gioitinh=rs.getInt(5)==1 ? "Nam" : "Nữ";
                    String Data[] = {rs.getString(1), rs.getString(3), rs.getString(4), gioitinh, rs.getString(7)};
                    tbModel.addRow(Data);
                }
                logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 xem d\u1eef li\u1ec7u nh\u00e2n vi\u00ean\n", username);

        } catch (SQLException ex) {
            Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

// btn chức năng
    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        btn_TimKiem.setBackground(Setting.SettingUI.btn_colorChange);
        jFrame_TimKiem_dialog.setVisible(true);
        dialog_Opened="timkiem";
        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng t\u00ecm ki\u1ebfm nh\u00e2n vi\u00ean\n", username);
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        btn_Them.setBackground(Setting.SettingUI.btn_colorChange);
        jTextField_CapNhatThemBox_ID.setText("");
        jTextField_CapNhatThemBox_Username.setText("");
        jTextField_CapNhatThemBox_HoTen.setText("");
        jTextField_CapNhatThemBox_SDT.setText("");
        jTextField_CapNhatThemBox_DiaChi.setText("");
        jTextField_CapNhatThemBox_Tuoi.setText("");
        jTextField_CapNhatThemBox_QueQuan.setText("");  
        jFrame_CapNhatThem_dialog.setVisible(true);  
        dialog_Opened="them";  
        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng th\u00eam nh\u00e2n vi\u00ean\n", username);
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_ChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChiTietActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        btn_ChiTiet.setBackground(Setting.SettingUI.btn_colorChange);
        jFrame_ChiTiet_dialog.setVisible(true);
        dialog_Opened="chitiet";
        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng xem th\u00f4ng tin chi ti\u1ebft nh\u00e2n vi\u00ean\n", username);
    }//GEN-LAST:event_btn_ChiTietActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        close_Dialog();
        this.setLocation(Setting.SettingUI.mainScreen_Location_Center);
        btn_Xoa.setBackground(Setting.SettingUI.btn_colorChange);
        dialog_Opened="xoa";
        if( jTable1.getSelectedRowCount()==1)
        {   
            tbModel=(DefaultTableModel)jTable1.getModel();
            String id=(String)tbModel.getValueAt(jTable1.getSelectedRow(), 0);
            int choice =JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa nhân viên id "+id +"?", "Xác nhận xóa",2);
            if(choice==0){
                ResultSet hdt=dbqr.ExcuQuery_GetRow("HOADONTRA", "Nhanvien_Id='"+id+"'");
                try {
                    if(hdt.next()==false)
                    {
                            dbqr.ExcuQuery_Delete("NHANVIEN","Id= '"+id+"'");
                            JOptionPane.showMessageDialog(null, "Xóa thành công!","Thông báo",1);
                            load_Table();
                            logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 x\u00f3a nh\u00e2n vi\u00ean id: {1}\n", new Object[]{username, id});
                    }
                    else{
                        // Mảng các lựa chọn
                        Object[] options = {"Hủy", "Vẫn Xóa"};

                        // Hiển thị hộp thoại tùy chọn
                        int selectedOption = JOptionPane.showOptionDialog(
                                null,                         // Parent component (null để trung tâm trên màn hình)
                                "Nhân viên tòn tại trong dữ liệu Hóa đơn trả, không thể xóa!",         // Nội dung hộp thoại
                                "Thông báo",         // Tiêu đề hộp thoại
                                JOptionPane.DEFAULT_OPTION,  // Kiểu hộp thoại
                                JOptionPane.WARNING_MESSAGE, // Kiểu thông điệp
                                null,                         // Icon (null để sử dụng icon mặc định)
                                options,                      // Mảng các lựa chọn
                                options[0]);                  // Lựa chọn mặc định

                        // Xử lý lựa chọn
                        if (selectedOption == 1) {
                            int ID=hdt.getInt(1);
                            String SDT;

                            int select=JOptionPane.showConfirmDialog(null, "Thông tin hóa đơn trả sẽ bị thay đổi ,Bạn vẫn muốn xóa?","Cảnh báo",JOptionPane.OK_CANCEL_OPTION,0);
                            if(select==JOptionPane.OK_OPTION)
                            {
                                dbqr.ExcuQuery_Update("HOADONTRA","Nhanvien_Id=null", "Id="+ID);
                                while(hdt.next()){    
                                    ID=hdt.getInt(1);
                                    dbqr.ExcuQuery_Update("HOADONTRA","Nhanvien_Id=null", "Id="+ID);
                                }
                                dbqr.ExcuQuery_Delete("NHANVIEN","Id= '"+id+"'");
                                JOptionPane.showMessageDialog(null, "Xóa thành công!","Thông báo",1);
                                load_Table();
                                logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 x\u00f3a nh\u00e2n vi\u00ean id: {1}\n", new Object[]{username, id});
                            }
                            else{}
                        } else {
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex); 
                }
                
            }
            
        }
        else JOptionPane.showMessageDialog(null, "Chọn dòng để xóa!","Thông báo",2);
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        btn_CapNhat.setBackground(Setting.SettingUI.btn_colorChange);
        jFrame_CapNhatThem_dialog.setVisible(true);  
        dialog_Opened="capnhat";
        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng c\u1eadp nh\u1eadt nh\u00e2n vi\u00ean \n", username);
    }//GEN-LAST:event_btn_CapNhatActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        close_Dialog();
        this.dispose();
        new ChucNang().setVisible(true);
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} tr\u1edf v\u1ec1 m\u00e0n h\u00ecnh ch\u1ecdn ch\u1ee9c n\u0103ng\n", username);
    }//GEN-LAST:event_btn_backActionPerformed

    
    
//btn mở dialog con
    private void btn_TimKiemBox_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemBox_closeActionPerformed
        // TODO add your handling code here: 
       animation_OpenDialog();
        this.setLocation(Setting.SettingUI.mainScreen_Location_Center);
    }//GEN-LAST:event_btn_TimKiemBox_closeActionPerformed

    private void btn_TimKiemBox_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemBox_searchActionPerformed
        // TODO add your handling code here:
        load_Table();
        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 t\u00ecm ki\u1ebfm th\u00f4ngg tin nh\u00e2n vi\u00ean, n\u1ed9i dung t\u00ecm ki\u1ebfm: {1}\n", new Object[]{username, jTextField_TimKiemBox_searchString.getText()});

    }//GEN-LAST:event_btn_TimKiemBox_searchActionPerformed

    private void btn_ChiTietBox_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChiTietBox_closeActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        this.setLocation(Setting.SettingUI.mainScreen_Location_Center);
    }//GEN-LAST:event_btn_ChiTietBox_closeActionPerformed

    private void btn_CapNhatThemBox_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatThemBox_CapNhatActionPerformed
        // TODO add your handling code here:
        if(checkText_isValid())
        {
            String id=jTextField_CapNhatThemBox_ID.getText();
            String Username=jTextField_CapNhatThemBox_Username.getText();
            String hoten=jTextField_CapNhatThemBox_HoTen.getText();
            String SDT=jTextField_CapNhatThemBox_SDT.getText();
            int gioitinh=jComboBox_CapNhatThemBox_GioiTinh.getItemAt(jComboBox_CapNhatThemBox_GioiTinh.getSelectedIndex()).equals("Nam") ? 1 : 0;
            String quequan=jTextField_CapNhatThemBox_QueQuan.getText();
            String dchi=jTextField_CapNhatThemBox_DiaChi.getText();
            int tuoi=Integer.parseInt(jTextField_CapNhatThemBox_Tuoi.getText());
            ResultSet nv=dbqr.ExcuQuery_GetRow("NHANVIEN", "Id='"+id+"'");
            ResultSet tk=dbqr.ExcuQuery_GetRow("TAIKHOAN", "Username='"+Username+"'");
            try {
                if(nv.next()){
                    System.out.println(1);
                    if(Username.equals("")){
                        dbqr.ExcuQuery_Update("NHANVIEN",
                                                    "Diachi =N'"+dchi +"',"
                                                            + "Username= null,"
                                                                    + "Hoten= N'"+hoten+"',"
                                                                            + "SDT= '"+SDT+"',"
                                                                                    + "Gioitinh ="+ gioitinh+","
                                                                                            + "Quequan ='"+ quequan+"',"
                                                                                                    + "Tuoi ="+ tuoi,
                                                   "Id= '"+id+"'");
                        JOptionPane.showMessageDialog(null, "Cập Nhật Nhân Viên thành công!","Thông báo",1);
                        load_Table();
                        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 c\u1eadp nh\u1eadt nh\u00e2n vi\u00ean id: {1}\n", new Object[]{username, id});
                    }
                    else if(tk.next()){
                        dbqr.ExcuQuery_Update("NHANVIEN",
                                                    "Diachi =N'"+dchi +"',"
                                                            + "Username= '"+Username+"',"
                                                                    + "Hoten= N'"+hoten+"',"
                                                                            + "SDT= '"+SDT+"',"
                                                                                    + "Gioitinh ="+ gioitinh+","
                                                                                            + "Quequan ='"+ quequan+"',"
                                                                                                    + "Tuoi ="+ tuoi,
                                                   "Id= '"+id+"'");
                        JOptionPane.showMessageDialog(null, "Cập Nhật Nhân Viên thành công!","Thông báo",1);
                        load_Table();
                        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 c\u1eadp nh\u1eadt nh\u00e2n vi\u00ean id: {1}\n", new Object[]{username, id});
                    }
                    else JOptionPane.showMessageDialog(null, "Tên đăng nhập không chính xác,vui lòng kiểm tra lại!","Thông báo",1);
                }
                else JOptionPane.showMessageDialog(null, "Nhân Viên không tồn tại, không thể cập nhật!","Thông báo",1);
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_CapNhatThemBox_CapNhatActionPerformed

    private void btn_CapNhatThemBox_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatThemBox_closeActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        this.setLocation(Setting.SettingUI.mainScreen_Location_Center);
    }//GEN-LAST:event_btn_CapNhatThemBox_closeActionPerformed

    private void btn_CapNhatThemBox_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatThemBox_ThemActionPerformed
        // TODO add your handling code here:
        String id=jTextField_CapNhatThemBox_ID.getText();
        String Username=jTextField_CapNhatThemBox_Username.getText();
        String hoten=jTextField_CapNhatThemBox_HoTen.getText();
        String SDT=jTextField_CapNhatThemBox_SDT.getText();
        int gioitinh=jComboBox_CapNhatThemBox_GioiTinh.getItemAt(jComboBox_CapNhatThemBox_GioiTinh.getSelectedIndex()).equals("Nam") ? 1 : 0;
        String quequan=jTextField_CapNhatThemBox_QueQuan.getText();
        String dchi=jTextField_CapNhatThemBox_DiaChi.getText();
        int tuoi=Integer.parseInt(jTextField_CapNhatThemBox_Tuoi.getText());
        ResultSet nv= dbqr.ExcuQuery_GetRow("NHANVIEN", "Id='"+id+"'");
        ResultSet tk=dbqr.ExcuQuery_GetRow("TAIKHOAN", "Username='"+Username+"'");
        if(checkText_isValid())
        {
            try {
                if(nv.next()==false)
                {
                    if(Username.equals("")){
                        dbqr.ExcuQuery_Add(
                                "INSERT [dbo].[NHANVIEN] ([Id], [Hoten], [Sdt],[Gioitinh], [Diachi], [Tuoi], [Quequan]) VALUES ("
                                        + "'"+id+"',"
                                        + "N'"+hoten+"',"
                                        + "'"+SDT+"',"
                                        + gioitinh+","
                                        + "N'"+dchi+"',"
                                        + tuoi+","
                                        + "N'"+quequan+"')");
                        JOptionPane.showMessageDialog(null, "Thêm Nhân Viên thành công!","Thông báo",1);
                        load_Table();
                        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 th\u00eam nh\u00e2n vi\u00ean id: {1}\n", new Object[]{username, id});
                    }
                    if(tk.next())
                    {
                        dbqr.ExcuQuery_Add(
                                "INSERT [dbo].[NHANVIEN] ([Id],[Username], [Hoten], [Sdt],[Gioitinh], [Diachi], [Tuoi], [Quequan]) VALUES ("
                                        + "'"+id+"',"
                                        + "'"+Username+"',"
                                        + "N'"+hoten+"',"
                                        + "'"+SDT+"',"
                                        + gioitinh+","
                                        + "N'"+dchi+"',"
                                        + tuoi+","
                                        + "N'"+quequan+"')");
                        JOptionPane.showMessageDialog(null, "Thêm Nhân Viên thành công!","Thông báo",1);
                        load_Table();
                        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 th\u00eam nh\u00e2n vi\u00ean id: {1}\n", new Object[]{username, id});
                    }
                }
                else JOptionPane.showMessageDialog(null, "Nhân Viên đã tồn tại hoặc tài khoản không chính xác, không thể thêm!","Thông báo",1);
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btn_CapNhatThemBox_ThemActionPerformed

    private void jTable1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseDragged
        // TODO add your handling code here:
        dialog_setText();
    }//GEN-LAST:event_jTable1MouseDragged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        dialog_setText();
    }//GEN-LAST:event_jTable1MouseClicked
    /**
    * Thiết lập dữ liệu cho các thành phần giao diện trong các hộp thoại "Cập nhật", "Chi tiết", "Trả sách", "Thuê sách" 
    * dựa trên dữ liệu của hàng được chọn trong bảng hoặc trạng thái của hộp thoại "Thêm".
    * Các thông tin sách bao gồm mã sách, hình ảnh, tên sách, tác giả, nhà xuất bản, năm xuất bản, số trang, số lượng,
    * giá sách, giá thuê, nội dung, vị trí.
    * 
    * Nếu đang mở hộp thoại "Thêm", chỉ mã sách sẽ được tự động điền vào.
    * Nếu đang mở hộp thoại "Cập nhật", dữ liệu sẽ được điền dựa trên dữ liệu của hàng được chọn trong bảng.
    * 
    * @see #get_row_Table(String, String)
    * @see #load_bookImage(String)
    */
   private void dialog_setText() {
       if (dialog_Opened.equals("them") == false) {
           tbModel = (DefaultTableModel) jTable1.getModel();
           String id;
           if (jTable1.getSelectedRowCount() == 1) {
               id=(String) tbModel.getValueAt(jTable1.getSelectedRow(), 0);
               ResultSet nv=dbqr.ExcuQuery_GetRow("NHANVIEN", "Id='"+id+"'");
               try {
                   nv.next();
                   ImageIcon bookImage = load_bookImage("https://artscimedia.case.edu/wp-content/uploads/sites/79/2016/12/14205134/no-user-image.gif");

                   // Dialog cập nhật 
                   jTextField_CapNhatThemBox_ID.setText(nv.getString(1));
                   jTextField_CapNhatThemBox_Username.setText(nv.getString(2));
                   jTextField_CapNhatThemBox_HoTen.setText(nv.getString(3));
                   jTextField_CapNhatThemBox_SDT.setText(nv.getString(4));
                   jComboBox_CapNhatThemBox_GioiTinh.setSelectedIndex(nv.getInt(5));
                   jTextField_CapNhatThemBox_DiaChi.setText(nv.getString(6));
                   jTextField_CapNhatThemBox_Tuoi.setText(nv.getString(7));
                   jTextField_CapNhatThemBox_QueQuan.setText(nv.getString(8));
                   // Dialog chi tiết
                   jLabel_ChiTietBox_Image.setIcon(bookImage);
                   String gioitinh=nv.getInt(5)==0 ?"Nữ":"Nam";
                   jTextPane_ChiTietBox_ThongTin.setText("Id: "+nv.getString(1)+"\n"
                                                        + "Username: "+nv.getString(2)+"\n"
                                                        + "Họ Tên: "+nv.getString(3)+"\n"
                                                        + "Số điện thoại: "+nv.getString(4)+"\n"
                                                        + "Giới Tính: "+gioitinh+"\n"
                                                        + "Địa Chỉ: "+nv.getString(6)+"\n"
                                                        + "Tuổi: "+nv.getString(7)+"\n"
                                                        + "Quê quán: "+nv.getString(8));
                    logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 xem chi ti\u1ebft nh\u00e2n vi\u00ean id: {1}\n", new Object[]{username, id});
                   
               } catch (SQLException ex) {
                   Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
               }
           } else {
               if (jTable1.getRowCount() == 0) {
                   JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu, không thể cập nhật!",
                           "Thông báo", 2);
               }
           }
       } else
           jTextField_CapNhatThemBox_ID.setText((String) tbModel.getValueAt(jTable1.getSelectedRow(), 0));
   }
    /**
    * Đóng các hộp thoại tương ứng với trạng thái hiện tại của ứng dụng và cài đặt lại giao diện.
    * Các hộp thoại được đóng bao gồm "Thêm", "Cập nhật", "Chi tiết", "Sắp xếp", "Tìm kiếm", "Trả sách", "Xóa", và "Thuê sách".
    * Cài đặt lại màu nền của các nút tương ứng trên giao diện người dùng.
    */
   private void close_Dialog() {
       if (dialog_Opened.equals("them")) {
           jFrame_CapNhatThem_dialog.setVisible(false);  
           btn_Them.setBackground(Setting.SettingUI.btn_colorDefault);
       }
       if (dialog_Opened.equals("timkiem")) {
           jFrame_TimKiem_dialog.setVisible(false);  
           btn_TimKiem.setBackground(Setting.SettingUI.btn_colorDefault);
       }
       if (dialog_Opened.equals("capnhat")) {
           jFrame_CapNhatThem_dialog.dispose(); 
           btn_CapNhat.setBackground(Setting.SettingUI.btn_colorDefault);
       }
       if (dialog_Opened.equals("chitiet")) {
           jFrame_ChiTiet_dialog.setVisible(false);
           btn_ChiTiet.setBackground(Setting.SettingUI.btn_colorDefault);
       }
       if (dialog_Opened.equals("xoa")) {
           btn_Xoa.setBackground(Setting.SettingUI.btn_colorDefault);    
       }
   }

    
    /**
    * Thực hiện hiệu ứng mở hộp thoại bằng cách đặt vị trí và đóng hộp thoại hiện tại.
    * Điều này có thể kết hợp với một hiệu ứng mở rộng khác để tạo hiệu ứng mở hộp thoại.
    */
    private void animation_OpenDialog() {
       this.setLocation(Setting.SettingUI.mainScreen_Location_Left); // Đặt vị trí của hộp thoại mới
       close_Dialog(); // Đóng hộp thoại hiện tại 
    }  
    
   /**
    * Tải hình ảnh sách từ URL và điều chỉnh kích thước để hiển thị trong giao diện.
    * 
    * @param url Đường dẫn URL đến hình ảnh sách.
    * @return ImageIcon của hình ảnh sách đã được điều chỉnh kích thước, hoặc null nếu xảy ra lỗi.
    */
    private ImageIcon load_bookImage(String url) {
       String imageURL = url;
       ImageIcon imageIcon = null;
       try {
           // Lấy hình ảnh từ URL
           ImageIcon img_book = new ImageIcon(new URL(imageURL));
           // Tính tỉ lệ giữa chiều rộng và chiều cao của hình ảnh
           double aspectRatio = (double) img_book.getIconWidth() / img_book.getIconHeight();
           // Chỉnh kích thước hình ảnh
           Image scaledImage = img_book.getImage().getScaledInstance(image_Width, (int) (image_Width * aspectRatio), Image.SCALE_SMOOTH);

           // Tạo một ImageIcon từ hình ảnh đã chỉnh kích thước
           imageIcon = new ImageIcon(scaledImage);

       } catch (IOException e) {
           // Xử lý ngoại lệ nếu có lỗi khi tải hình ảnh
           imageURL="https://st4.depositphotos.com/14953852/24787/v/450/depositphotos_247872612-stock-illustration-no-image-available-icon-vector.jpg";
           // Lấy hình ảnh từ URL
           ImageIcon img_book;
           try {
               img_book = new ImageIcon(new URL(imageURL));
               // Tính tỉ lệ giữa chiều rộng và chiều cao của hình ảnh
                double aspectRatio = (double) img_book.getIconWidth() / img_book.getIconHeight();
                // Chỉnh kích thước hình ảnh
                Image scaledImage = img_book.getImage().getScaledInstance(image_Width, (int) (image_Width * aspectRatio), Image.SCALE_SMOOTH);

                // Tạo một ImageIcon từ hình ảnh đã chỉnh kích thước
                imageIcon = new ImageIcon(scaledImage);
           } catch (MalformedURLException ex) {
               Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
           }
           
       }
       return imageIcon;
    }
   
   
   /**
    * Thiết lập quyền truy cập và hiển thị các thành phần giao diện dựa trên vai trò người dùng.
    * 
    * @param Role Vai trò của người dùng ("Nhân Viên", "Quản Lý", hoặc "Khách Hàng").
    */
   private void setRole(String Role) {
        switch (Role) {
            case "Nhân Viên" -> {
            }
            case "Quản Lý" -> {
            }
            case "Khách Hàng" -> {
            }
            default -> {
            }
        }
        // Cài đặt cho vai trò Nhân Viên (có thể thêm các cài đặt khác nếu cần)
        // Cài đặt cho vai trò Quản Lý (có thể thêm các cài đặt khác nếu cần)
           }
   
   
   /**
    * Chuyển đổi các chuỗi mô tả sắp xếp từ giao diện người dùng thành các giá trị tương ứng của truy vấn cơ sở dữ liệu.
    * 
    * @param s Chuỗi mô tả sắp xếp từ giao diện người dùng.
    * @return Giá trị tương ứng của truy vấn cơ sở dữ liệu, hoặc chuỗi rỗng nếu không tìm thấy giá trị phù hợp.
    */
   private String convertToDbString(String s) {
       if (s.equals("Tăng dần")) return "ASC";
       if (s.equals("Giảm dần")) return "DESC";
       if (s.equals("Id")) return "Id";
       if (s.equals("Họ Tên")) return "Hoten";
       if (s.equals("Tuổi")) return "Tuoi";
       if (s.equals("Quê")) return "Quequan";
       if (s.equals("Số điện thoại")) return "Sdt";
       return "";
   }

   /**
    * Kiểm tra tính hợp lệ của các thông tin nhập liệu dựa trên loại hộp thoại đang mở và lựa chọn được chọn.
    * Hiển thị thông báo lỗi nếu có lỗi và trả về true nếu dữ liệu hợp lệ, ngược lại trả về false.
    * 
    * @param choice Lựa chọn đại diện cho hộp thoại hiện tại (0: Thêm/Cập nhật sách, 1: Trả sách, 2: Thuê sách).
    * @return True nếu dữ liệu nhập liệu hợp lệ, ngược lại trả về false.
    */
   private boolean checkText_isValid() {
       String error_String = "";

       if (dialog_Opened.equals("them") || dialog_Opened.equals("capnhat")) {
           // Kiểm tra thông tin khi thêm/cập nhật sách
           String hoten = jTextField_CapNhatThemBox_HoTen.getText().equals("") ? error_String += "Họ Tên- " : "";
           String id = jTextField_CapNhatThemBox_ID.getText().equals("") ? error_String += "ID- " : "";
           String quequan = jTextField_CapNhatThemBox_QueQuan.getText().equals("") ? error_String += "Quê Quán- " : "";
           String dchi = jTextField_CapNhatThemBox_DiaChi.getText().equals("") ? error_String += "Đia Chỉ- " : "";
           String SDT = jTextField_CapNhatThemBox_SDT.getText();
           if (Setting.SettingUI.isValidPhoneNumber(SDT) == false) {
               error_String += "Số Điện Thoại- ";
           }
           try {
               int Tuoi = jTextField_CapNhatThemBox_Tuoi.getText().equals("") ? -1
                       : Integer.parseInt(jTextField_CapNhatThemBox_Tuoi.getText());
               if (Tuoi >= 100 || Tuoi <= 5) {
                   error_String += "Tuổi- ";
               }
           } catch (NumberFormatException e) {
               error_String += "Tuổi- ";
           }
       }
       if (error_String.equals("") == false) {
           JOptionPane.showMessageDialog(null, "Thông tin " + error_String + "không chính xác, vui lòng nhập lại!",
                   "Nhập sai thông tin", 2);
           return false;
       }
       return true;
   }

   /**
    * Hiển thị một hộp thoại tùy chọn với các lựa chọn được cung cấp và trả về lựa chọn được chọn.
    * 
    * @param options Mảng các đối tượng đại diện cho các lựa chọn hiển thị trong hộp thoại.
    * @return Số nguyên đại diện cho lựa chọn được chọn từ hộp thoại. 
    *         Nếu không có lựa chọn nào được chọn hoặc hộp thoại bị đóng, trả về giá trị mặc định của JOptionPane.
    */
   private int optionPane(Object[] options) {
        // Hiển thị JOptionPane với các lựa chọn và một thông điệp (hình ảnh có thể thêm vào nếu cần)
        int choice = JOptionPane.showOptionDialog(
                null,
                "Bạn muốn: ",
                "Chọn Chức Năng",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null, // Thay "icon.png" bằng đường dẫn của hình ảnh bạn muốn sử dụng
                options,
                options[0]
        );
        return choice;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuanLyNhanVien().setVisible(true);
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_CapNhatThemBox_CapNhat;
    private javax.swing.JButton btn_CapNhatThemBox_Them;
    private javax.swing.JButton btn_CapNhatThemBox_close;
    private javax.swing.JButton btn_ChiTiet;
    private javax.swing.JButton btn_ChiTietBox_close;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_TimKiemBox_close;
    private javax.swing.JButton btn_TimKiemBox_search;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<String> jComboBox_CapNhatThemBox_GioiTinh;
    private javax.swing.JComboBox<String> jComboBox_TimKiemBox_item;
    private javax.swing.JFrame jFrame_CapNhatThem_dialog;
    private javax.swing.JFrame jFrame_ChiTiet_dialog;
    private javax.swing.JFrame jFrame_TimKiem_dialog;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel_ChiTietBox_Image;
    private javax.swing.JLabel jLabel_mainTittle;
    private javax.swing.JPanel jPanel_CapNhatThemBox;
    private javax.swing.JPanel jPanel_ChiTietBox;
    private javax.swing.JPanel jPanel_ChiTietBox_Image;
    private javax.swing.JPanel jPanel_ChucNang_main;
    private javax.swing.JPanel jPanel_TimKiemBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_ChiTietBox_Content;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_CapNhatThemBox_DiaChi;
    private javax.swing.JTextField jTextField_CapNhatThemBox_HoTen;
    private javax.swing.JTextField jTextField_CapNhatThemBox_ID;
    private javax.swing.JTextField jTextField_CapNhatThemBox_QueQuan;
    private javax.swing.JTextField jTextField_CapNhatThemBox_SDT;
    private javax.swing.JTextField jTextField_CapNhatThemBox_Tuoi;
    private javax.swing.JTextField jTextField_CapNhatThemBox_Username;
    private javax.swing.JTextField jTextField_TimKiemBox_searchString;
    private javax.swing.JTextPane jTextPane_ChiTietBox_ThongTin;
    // End of variables declaration//GEN-END:variables

    private Image Image(ImageIcon img_bookIcon) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
