/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms    @Override
    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Insets getBorderInsets(Component c) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean isBorderOpaque() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
/JFrame.java to edit this template
 */
package UI;


import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import DB.DbQuery;
import Setting.DesEncrypt;

import javax.crypto.Cipher;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class QuanLyTaiKhoan extends javax.swing.JFrame{

    /**
     * Creates new form DangNhap
     */
    private final ImageIcon img_Back;
    private final String role=DangNhap.Role;
    private DefaultTableModel tbModel;
    private final int image_Width=292;
    private final DbQuery dbqr=new DbQuery();
    private ResultSet rs;
    private String dialog_Opened="";
    private final String username=DangNhap.Username;
    private static final Logger logger = Setting.SettingUI.logger;

    public QuanLyTaiKhoan() {
        img_Back=new ImageIcon(new ImageIcon(getClass().getResource("/Image/backicon.png")).getImage().getScaledInstance(45, 25, Image.SCALE_SMOOTH));
        initComponents();
        setRole(role);
        load_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_TimKiem_dialog = new javax.swing.JFrame();
        jPanel_TimKiemBox = new javax.swing.JPanel();
        jTextField_TimKiemBox_searchString = new javax.swing.JTextField();
        btn_TimKiemBox_search = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_TimKiemBox_close = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        jComboBox_TimKiemBox_item = new javax.swing.JComboBox<>();
        jFrame_CapNhatThem_dialog = new javax.swing.JFrame();
        jPanel_CapNhatThemBox = new javax.swing.JPanel();
        btn_CapNhatThemBox_CapNhat = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_CapNhatThemBox_close = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        jTextField_CapNhatThemBox_Username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_CapNhatThemBox_Them = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        jPasswordField_CapNhatThemBox_AgainPassWord = new javax.swing.JPasswordField();
        jPasswordField_CapNhatThemBox_PassWord = new javax.swing.JPasswordField();
        jComboBox_CapNhatThemBox_Role = new javax.swing.JComboBox<>();
        jPanel_ChucNang_main = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_TimKiem = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_Them = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_Xoa = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        btn_CapNhat = Setting.SettingUI.createRoundedButton(0.5,0.5,20);
        jLabel_mainTittle = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        jFrame_TimKiem_dialog.setLocation(Setting.SettingUI.dialog_Location);
        jFrame_TimKiem_dialog.setMinimumSize(new java.awt.Dimension(466, 143));
        jFrame_TimKiem_dialog.setUndecorated(true);
        jFrame_TimKiem_dialog.setResizable(false);

        jPanel_TimKiemBox.setBackground(new java.awt.Color(255, 138, 20));
        jPanel_TimKiemBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextField_TimKiemBox_searchString.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btn_TimKiemBox_search.setBackground(new java.awt.Color(250, 215, 172));
        btn_TimKiemBox_search.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_TimKiemBox_search.setText("Tìm");
        btn_TimKiemBox_search.setBorderPainted(false);
        btn_TimKiemBox_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemBox_searchActionPerformed(evt);
            }
        });

        btn_TimKiemBox_close.setBackground(new java.awt.Color(250, 215, 172));
        btn_TimKiemBox_close.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_TimKiemBox_close.setText("Đóng");
        btn_TimKiemBox_close.setBorderPainted(false);
        btn_TimKiemBox_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemBox_closeActionPerformed(evt);
            }
        });

        jComboBox_TimKiemBox_item.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_TimKiemBox_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tài Khoản" }));

        javax.swing.GroupLayout jPanel_TimKiemBoxLayout = new javax.swing.GroupLayout(jPanel_TimKiemBox);
        jPanel_TimKiemBox.setLayout(jPanel_TimKiemBoxLayout);
        jPanel_TimKiemBoxLayout.setHorizontalGroup(
            jPanel_TimKiemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TimKiemBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_TimKiemBox_item, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_TimKiemBox_searchString)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TimKiemBoxLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btn_TimKiemBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btn_TimKiemBox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel_TimKiemBoxLayout.setVerticalGroup(
            jPanel_TimKiemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TimKiemBoxLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_TimKiemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_TimKiemBox_searchString, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jComboBox_TimKiemBox_item))
                .addGap(18, 18, 18)
                .addGroup(jPanel_TimKiemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TimKiemBox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiemBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame_TimKiem_dialogLayout = new javax.swing.GroupLayout(jFrame_TimKiem_dialog.getContentPane());
        jFrame_TimKiem_dialog.getContentPane().setLayout(jFrame_TimKiem_dialogLayout);
        jFrame_TimKiem_dialogLayout.setHorizontalGroup(
            jFrame_TimKiem_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_TimKiemBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame_TimKiem_dialogLayout.setVerticalGroup(
            jFrame_TimKiem_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_TimKiemBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame_CapNhatThem_dialog.setLocation(Setting.SettingUI.dialog_Location);
        jFrame_CapNhatThem_dialog.setMinimumSize(new java.awt.Dimension(466, 297));
        jFrame_CapNhatThem_dialog.setUndecorated(true);

        jPanel_CapNhatThemBox.setBackground(new java.awt.Color(255, 138, 20));
        jPanel_CapNhatThemBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_CapNhatThemBox.setMaximumSize(new java.awt.Dimension(466, 623));
        jPanel_CapNhatThemBox.setPreferredSize(new java.awt.Dimension(466, 623));

        btn_CapNhatThemBox_CapNhat.setBackground(new java.awt.Color(250, 215, 172));
        btn_CapNhatThemBox_CapNhat.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_CapNhatThemBox_CapNhat.setText("Cập Nhật");
        btn_CapNhatThemBox_CapNhat.setBorderPainted(false);
        btn_CapNhatThemBox_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatThemBox_CapNhatActionPerformed(evt);
            }
        });

        btn_CapNhatThemBox_close.setBackground(new java.awt.Color(250, 215, 172));
        btn_CapNhatThemBox_close.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_CapNhatThemBox_close.setText("Đóng");
        btn_CapNhatThemBox_close.setBorderPainted(false);
        btn_CapNhatThemBox_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatThemBox_closeActionPerformed(evt);
            }
        });

        jTextField_CapNhatThemBox_Username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField_CapNhatThemBox_Username.setMaximumSize(new java.awt.Dimension(7, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Tài Khoản:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Mật Khẩu:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Xác Thực MK:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Phân Quyền:");

        btn_CapNhatThemBox_Them.setBackground(new java.awt.Color(250, 215, 172));
        btn_CapNhatThemBox_Them.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_CapNhatThemBox_Them.setText("Thêm");
        btn_CapNhatThemBox_Them.setBorderPainted(false);
        btn_CapNhatThemBox_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatThemBox_ThemActionPerformed(evt);
            }
        });

        jPasswordField_CapNhatThemBox_AgainPassWord.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jPasswordField_CapNhatThemBox_PassWord.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jComboBox_CapNhatThemBox_Role.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBox_CapNhatThemBox_Role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách Hàng", "Nhân Viên", "Quản Lý" }));

        javax.swing.GroupLayout jPanel_CapNhatThemBoxLayout = new javax.swing.GroupLayout(jPanel_CapNhatThemBox);
        jPanel_CapNhatThemBox.setLayout(jPanel_CapNhatThemBoxLayout);
        jPanel_CapNhatThemBoxLayout.setHorizontalGroup(
            jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_CapNhatThemBox_Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField_CapNhatThemBox_AgainPassWord)
                    .addComponent(jPasswordField_CapNhatThemBox_PassWord, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jComboBox_CapNhatThemBox_Role, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
            .addGroup(jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_CapNhatThemBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_CapNhatThemBox_CapNhat)
                .addGap(35, 35, 35)
                .addComponent(btn_CapNhatThemBox_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_CapNhatThemBoxLayout.setVerticalGroup(
            jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CapNhatThemBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_CapNhatThemBox_Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_CapNhatThemBox_PassWord))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_CapNhatThemBox_AgainPassWord))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_CapNhatThemBox_Role))
                .addGap(18, 18, 18)
                .addGroup(jPanel_CapNhatThemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CapNhatThemBox_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CapNhatThemBox_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CapNhatThemBox_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame_CapNhatThem_dialogLayout = new javax.swing.GroupLayout(jFrame_CapNhatThem_dialog.getContentPane());
        jFrame_CapNhatThem_dialog.getContentPane().setLayout(jFrame_CapNhatThem_dialogLayout);
        jFrame_CapNhatThem_dialogLayout.setHorizontalGroup(
            jFrame_CapNhatThem_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_CapNhatThemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jFrame_CapNhatThem_dialogLayout.setVerticalGroup(
            jFrame_CapNhatThem_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_CapNhatThemBox, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(600, 300));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1063, 623));
        setMinimumSize(new java.awt.Dimension(1063, 623));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1063, 623));
        setResizable(false);

        jPanel_ChucNang_main.setBackground(Setting.SettingUI.UI_colorDefault);
        jPanel_ChucNang_main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_ChucNang_main.setToolTipText("");
        jPanel_ChucNang_main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tài Khoản", "Mã Hóa Tài Khoản", "Phân Quyền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(30);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowHorizontalLines(false);
        jTable1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTable1MouseDragged(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_TimKiem.setBackground(new java.awt.Color(250, 215, 172));
        btn_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_TimKiem.setText("Tìm Kiếm");
        btn_TimKiem.setBorderPainted(false);
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_Them.setBackground(new java.awt.Color(250, 215, 172));
        btn_Them.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.setBorderPainted(false);
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(250, 215, 172));
        btn_Xoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.setBorderPainted(false);
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_CapNhat.setBackground(new java.awt.Color(250, 215, 172));
        btn_CapNhat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_CapNhat.setText("Cập Nhật");
        btn_CapNhat.setBorderPainted(false);
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        jLabel_mainTittle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_mainTittle.setText("Quản Lý Tài Khoản");

        btn_back.setBackground(new java.awt.Color(250, 215, 172));
        btn_back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_back.setIcon(img_Back);
        btn_back.setBorderPainted(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ChucNang_mainLayout = new javax.swing.GroupLayout(jPanel_ChucNang_main);
        jPanel_ChucNang_main.setLayout(jPanel_ChucNang_mainLayout);
        jPanel_ChucNang_mainLayout.setHorizontalGroup(
            jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_mainTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
            .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                    .addGap(892, 892, 892)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(169, Short.MAX_VALUE)))
            .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE))
        );
        jPanel_ChucNang_mainLayout.setVerticalGroup(
            jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_mainTittle)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ChucNang_mainLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btn_TimKiem)
                .addGap(27, 27, 27)
                .addComponent(btn_Them)
                .addGap(31, 31, 31)
                .addComponent(btn_CapNhat)
                .addGap(31, 31, 31)
                .addComponent(btn_Xoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChucNang_mainLayout.createSequentialGroup()
                    .addGap(0, 75, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel_ChucNang_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChucNang_mainLayout.createSequentialGroup()
                    .addContainerGap(75, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(542, 542, 542)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ChucNang_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ChucNang_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1063, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

/**
 * Phương thức này thực hiện việc tải dữ liệu từ cơ sở dữ liệu và hiển thị nó trong bảng.
 * Dữ liệu được lấy dựa trên các thông tin nhập từ các thành phần giao diện như combobox và textbox.
 * 
 * @throws SQLException Nếu có lỗi xảy ra trong quá trình truy vấn cơ sở dữ liệu.
 */
    private void load_Table()
    {
        if(tbModel!=null)
            tbModel.setRowCount(0);
        // Lấy thông tin từ các thành phần giao diện
        String typeSearch = convertToDbString(jComboBox_TimKiemBox_item.getItemAt(jComboBox_TimKiemBox_item.getSelectedIndex()));
        String searchString = jTextField_TimKiemBox_searchString.getText();
        try {
                rs = dbqr.ExcuQuery_GetTable("TAIKHOAN",
                        typeSearch + " like N'%" + searchString + "%'",
                        "Role ASC");

                // Hiển thị dữ liệu trong bảng
                tbModel = (DefaultTableModel) jTable1.getModel();
                while (rs.next()) {
                    String Data[] = {rs.getString(1), rs.getString(2), rs.getString(3)};
                    tbModel.addRow(Data);
                }
                logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 xem danh s\u00e1ch t\u00e0i kho\u1ea3n\n", username);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

// btn chức năng
    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        btn_TimKiem.setBackground(Setting.SettingUI.btn_colorChange);
        jFrame_TimKiem_dialog.setVisible(true);
        dialog_Opened="timkiem";
        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng t\u00ecm ki\u1ebfm\n", username);
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        btn_Them.setBackground(Setting.SettingUI.btn_colorChange);
        jTextField_CapNhatThemBox_Username.setText("");
        jPasswordField_CapNhatThemBox_PassWord.setText("");
        jPasswordField_CapNhatThemBox_AgainPassWord.setText("");
        jComboBox_CapNhatThemBox_Role.setSelectedIndex(0);
        jFrame_CapNhatThem_dialog.setVisible(true);  
        dialog_Opened="them";  
        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng th\u00eam\n", username);
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        close_Dialog();
        this.setLocation(Setting.SettingUI.mainScreen_Location_Center);
        btn_Xoa.setBackground(Setting.SettingUI.btn_colorChange);
        dialog_Opened="xoa";
        tbModel=(DefaultTableModel)jTable1.getModel();
        String Username=(String)tbModel.getValueAt(jTable1.getSelectedRow(), 0);
        int choice =JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa tài khoản "+Username +"?", "Xác nhận xóa",2);
        if(choice==0){
            ResultSet nv=dbqr.ExcuQuery_GetRow("NHANVIEN", "Username='"+Username+"'");
            try {
                if(nv.next()==false)
                {
                    dbqr.ExcuQuery_Delete("TAIKHOAN","Username= '"+Username+"'");
                    JOptionPane.showMessageDialog(null, "Xóa thành công!","Thông báo",1);
                    load_Table();
                    logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 x\u00f3a t\u00e0i kho\u1ea3n {1}\n", new Object[]{username, Username});

                }
                else{
                    String id=nv.getString(1);
                    dbqr.ExcuQuery_Update("NHANVIEN",
                                            "Username= null",
                                               "Id= '"+id+"'");
                    dbqr.ExcuQuery_Delete("TAIKHOAN","Username= '"+Username+"'");
                    JOptionPane.showMessageDialog(null, "Xóa thành công!","Thông báo",1);
                    load_Table();
                    logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 x\u00f3a t\u00e0i kho\u1ea3n {1}\n", new Object[]{username, Username});                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex); 
            }
                
            }
            
        else JOptionPane.showMessageDialog(null, "Chọn dòng để xóa!","Thông báo",2);
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        btn_CapNhat.setBackground(Setting.SettingUI.btn_colorChange);
        jFrame_CapNhatThem_dialog.setVisible(true);  
        dialog_Opened="capnhat";
        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 s\u1eed d\u1ee5ng ch\u1ee9c n\u0103ng c\u1eadp nh\u1eadt\n", username);
    }//GEN-LAST:event_btn_CapNhatActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        close_Dialog();
        this.dispose();
        new ChucNang().setVisible(true);
        logger.log(Level.INFO, " Ng\u01b0\u1eddi d\u00f9ng {0} tr\u1edf v\u1ec1 m\u00e0n h\u00ecnh ch\u1ecdn ch\u1ee9c n\u0103ng\n", username);
    }//GEN-LAST:event_btn_backActionPerformed

    
    
//btn mở dialog con
    private void btn_TimKiemBox_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemBox_closeActionPerformed
        // TODO add your handling code here: 
       animation_OpenDialog();
        this.setLocation(Setting.SettingUI.mainScreen_Location_Center);
    }//GEN-LAST:event_btn_TimKiemBox_closeActionPerformed

    private void btn_TimKiemBox_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemBox_searchActionPerformed
        // TODO add your handling code here:
        load_Table();
        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 t\u00ecm ki\u1ebfm th\u00f4ngg tin t\u00e0i kh\u1ecfan, n\u1ed9i dung t\u00ecm ki\u1ebfm: {1}\n", new Object[]{username, jTextField_TimKiemBox_searchString.getText()});
    }//GEN-LAST:event_btn_TimKiemBox_searchActionPerformed

    private void btn_CapNhatThemBox_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatThemBox_CapNhatActionPerformed
        // TODO add your handling code here:
        if(jPasswordField_CapNhatThemBox_PassWord.getText().equals("")&&jPasswordField_CapNhatThemBox_AgainPassWord.getText().equals(""))
        {
            String Username=jTextField_CapNhatThemBox_Username.getText();
            String Role=jComboBox_CapNhatThemBox_Role.getItemAt(jComboBox_CapNhatThemBox_Role.getSelectedIndex());
            ResultSet tk= dbqr.ExcuQuery_GetRow("TAIKHOAN", "Username='"+Username+"'");
            try {
                if(tk.next()==false)
                {
                    JOptionPane.showMessageDialog(null, "Tên đăng nhập không tồn tại, không thể cập nhật!","Thông báo",1);
                }
                else
                {
                    dbqr.ExcuQuery_Update("TAIKHOAN", "Role=N'"+Role+"'", "Username='"+Username+"'");
                    JOptionPane.showMessageDialog(null, "Cập nhật thành công!","Thông báo",1);
                    load_Table();
                    logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 c\u1eadp nh\u1eadt t\u00e0i kho\u1ea3n {1}\n", new Object[]{username, Username});
                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            if(checkText_isValid()){
                DesEncrypt encrypt=new DesEncrypt();
                String Username=jTextField_CapNhatThemBox_Username.getText();
                String Role=jComboBox_CapNhatThemBox_Role.getItemAt(jComboBox_CapNhatThemBox_Role.getSelectedIndex());
                ResultSet tk= dbqr.ExcuQuery_GetRow("TAIKHOAN", "Username='"+Username+"'");
                try {
                    if(tk.next()==false)
                    {
                        JOptionPane.showMessageDialog(null, "Tên đăng nhập không tồn tại, không thể cập nhật!","Thông báo",1);
                    }
                    else
                    {
                        
                        String encryptPass = encrypt.encryptOrDecrypt(jPasswordField_CapNhatThemBox_AgainPassWord.getText(),Cipher.ENCRYPT_MODE,Username); 
                        dbqr.ExcuQuery_Update("TAIKHOAN",
                                                "Role=N'"+Role+"'," +
                                                "encryptPass='"+encryptPass+"'",
                                                "Username='"+Username+"'");
                        JOptionPane.showMessageDialog(null, "Cập nhật thành công!","Thông báo",1);
                        load_Table();
                        logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 c\u1eadp nh\u1eadt t\u00e0i kho\u1ea3n {1}\n", new Object[]{username, Username});
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Throwable ex) {
                    Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }  
    }//GEN-LAST:event_btn_CapNhatThemBox_CapNhatActionPerformed

    private void btn_CapNhatThemBox_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatThemBox_closeActionPerformed
        // TODO add your handling code here:
        animation_OpenDialog();
        this.setLocation(Setting.SettingUI.mainScreen_Location_Center);
    }//GEN-LAST:event_btn_CapNhatThemBox_closeActionPerformed

    private void btn_CapNhatThemBox_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatThemBox_ThemActionPerformed
        // TODO add your handling code here:
        if(checkText_isValid()){
            DesEncrypt encrypt=new DesEncrypt();
            String Username=jTextField_CapNhatThemBox_Username.getText();
            String Role=jComboBox_CapNhatThemBox_Role.getItemAt(jComboBox_CapNhatThemBox_Role.getSelectedIndex());
            ResultSet tk= dbqr.ExcuQuery_GetRow("TAIKHOAN", "Username='"+Username+"'");
            try {
                if(tk.next())
                {
                    JOptionPane.showMessageDialog(null, "Tên đăng nhập đã tồn tại, không thể thêm!","Thông báo",1);
                }
                else
                {
                    String encryptPass = encrypt.encryptOrDecrypt(jPasswordField_CapNhatThemBox_AgainPassWord.getText(),Cipher.ENCRYPT_MODE,Username); 
                    dbqr.ExcuQuery_Add(
                        "INSERT [dbo].[TAIKHOAN] ([Username],[encryptPass], [Role] ) VALUES ("
                        + "'"+Username+"',"
                            + "'"+encryptPass+"',"
                                    + "N'"+Role+"')");
                    System.out.println("EncryptPass="+encryptPass);
                    JOptionPane.showMessageDialog(null, "Thêm thành công!","Thông báo",1);
                    load_Table();
                    logger.log(Level.INFO, "Ng\u01b0\u1eddi d\u00f9ng {0} \u0111\u00e3 th\u00eam t\u00e0i kho\u1ea3n {1}\n", new Object[]{username, Username});
                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Throwable ex) {
                Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btn_CapNhatThemBox_ThemActionPerformed

    private void jTable1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseDragged
        // TODO add your handling code here:
        dialog_setText();
    }//GEN-LAST:event_jTable1MouseDragged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        dialog_setText();
    }//GEN-LAST:event_jTable1MouseClicked
    /**
    * Thiết lập dữ liệu cho các thành phần giao diện trong các hộp thoại "Cập nhật", "Chi tiết", "Trả sách", "Thuê sách" 
    * dựa trên dữ liệu của hàng được chọn trong bảng hoặc trạng thái của hộp thoại "Thêm".
    * Các thông tin sách bao gồm mã sách, hình ảnh, tên sách, tác giả, nhà xuất bản, năm xuất bản, số trang, số lượng,
    * giá sách, giá thuê, nội dung, vị trí.
    * 
    * Nếu đang mở hộp thoại "Thêm", chỉ mã sách sẽ được tự động điền vào.
    * Nếu đang mở hộp thoại "Cập nhật", dữ liệu sẽ được điền dựa trên dữ liệu của hàng được chọn trong bảng.
    * 
    * @see #get_row_Table(String, String)
    * @see #load_bookImage(String)
    */
   private void dialog_setText() {
       if (dialog_Opened.equals("them") == false) {
           tbModel = (DefaultTableModel) jTable1.getModel();
           String Username;
           if (jTable1.getSelectedRowCount() == 1) {
               Username=(String) tbModel.getValueAt(jTable1.getSelectedRow(), 0);
                ResultSet tk=dbqr.ExcuQuery_GetRow("TAIKHOAN", "Username='"+Username+"'");
               try {
                   tk.next();
                   // Dialog cập nhật 
                   jTextField_CapNhatThemBox_Username.setText(tk.getString(1));
                   jPasswordField_CapNhatThemBox_PassWord.setText("");
                   jPasswordField_CapNhatThemBox_AgainPassWord.setText("");
                   String Role=tk.getString(3);
                   if(Role.equals("Khách Hàng"))
                       jComboBox_CapNhatThemBox_Role.setSelectedIndex(0);
                   if(Role.equals("Nhân Viên"))
                       jComboBox_CapNhatThemBox_Role.setSelectedIndex(1);
                   if(Role.equals("Quản Lý"))
                       jComboBox_CapNhatThemBox_Role.setSelectedIndex(2);
            
               } catch (SQLException ex) {
                   Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
               } catch (Throwable ex) {
                   Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
               }
           } else {
               if (jTable1.getRowCount() == 0) {
                   JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu, không thể cập nhật!",
                           "Thông báo", 2);
               }
           }
       } else
           jTextField_CapNhatThemBox_Username.setText((String) tbModel.getValueAt(jTable1.getSelectedRow(), 0));
   }
    /**
    * Đóng các hộp thoại tương ứng với trạng thái hiện tại của ứng dụng và cài đặt lại giao diện.
    * Các hộp thoại được đóng bao gồm "Thêm", "Cập nhật", "Chi tiết", "Sắp xếp", "Tìm kiếm", "Trả sách", "Xóa", và "Thuê sách".
    * Cài đặt lại màu nền của các nút tương ứng trên giao diện người dùng.
    */
   private void close_Dialog() {
       if (dialog_Opened.equals("them")) {
           jFrame_CapNhatThem_dialog.setVisible(false);  
           btn_Them.setBackground(Setting.SettingUI.btn_colorDefault);
       }
       if (dialog_Opened.equals("capnhat")) {
           jFrame_CapNhatThem_dialog.dispose(); 
           btn_CapNhat.setBackground(Setting.SettingUI.btn_colorDefault);
       }
       if (dialog_Opened.equals("timkiem")) {
           jFrame_TimKiem_dialog.setVisible(false);
           btn_TimKiem.setBackground(Setting.SettingUI.btn_colorDefault);
       }

   }

    
    /**
    * Thực hiện hiệu ứng mở hộp thoại bằng cách đặt vị trí và đóng hộp thoại hiện tại.
    * Điều này có thể kết hợp với một hiệu ứng mở rộng khác để tạo hiệu ứng mở hộp thoại.
    */
    private void animation_OpenDialog() {
       this.setLocation(Setting.SettingUI.mainScreen_Location_Left); // Đặt vị trí của hộp thoại mới
       close_Dialog(); // Đóng hộp thoại hiện tại 
    }  

   
   /**
    * Thiết lập quyền truy cập và hiển thị các thành phần giao diện dựa trên vai trò người dùng.
    * 
    * @param Role Vai trò của người dùng ("Nhân Viên", "Quản Lý", hoặc "Khách Hàng").
    */
   private void setRole(String Role) {
        switch (Role) {
            case "Nhân Viên" -> {
            }
            case "Quản Lý" -> {
            }
            case "Khách Hàng" -> {

            }
            default -> {
            }
        }
        // Cài đặt cho vai trò Nhân Viên (có thể thêm các cài đặt khác nếu cần)
        // Cài đặt cho vai trò Quản Lý (có thể thêm các cài đặt khác nếu cần)
           }
   
   
   /**
    * Chuyển đổi các chuỗi mô tả sắp xếp từ giao diện người dùng thành các giá trị tương ứng của truy vấn cơ sở dữ liệu.
    * 
    * @param s Chuỗi mô tả sắp xếp từ giao diện người dùng.
    * @return Giá trị tương ứng của truy vấn cơ sở dữ liệu, hoặc chuỗi rỗng nếu không tìm thấy giá trị phù hợp.
    */
   private String convertToDbString(String s) {
       if (s.equals("Tăng dần")) return "ASC";
       if (s.equals("Giảm dần")) return "DESC";
       if (s.equals("Tài Khoản")) return "Username";
       return "";
   }

   /**
    * Kiểm tra tính hợp lệ của các thông tin nhập liệu dựa trên loại hộp thoại đang mở và lựa chọn được chọn.
    * Hiển thị thông báo lỗi nếu có lỗi và trả về true nếu dữ liệu hợp lệ, ngược lại trả về false.
    * 
    * @param choice Lựa chọn đại diện cho hộp thoại hiện tại (0: Thêm/Cập nhật sách, 1: Trả sách, 2: Thuê sách).
    * @return True nếu dữ liệu nhập liệu hợp lệ, ngược lại trả về false.
    */
   private boolean checkText_isValid() {
       String error_String = "";

       if (dialog_Opened.equals("them") || dialog_Opened.equals("capnhat")) {
               //Kiểm tra thông tin khi thêm/cập nhật sách
               String Username = jTextField_CapNhatThemBox_Username.getText().equals("") ? error_String += "Username- " : "";
                // Kiểm tra thông tin khi trả sách
               String password = jPasswordField_CapNhatThemBox_PassWord.getText();
               if (Setting.SettingUI.isValidPassWord(password) == false) {
                   error_String += "Mật Khẩu cần 8 kí tự trở lên- ";
               }
               if(jPasswordField_CapNhatThemBox_AgainPassWord.getText().equals("")||
                       jPasswordField_CapNhatThemBox_AgainPassWord.getText().equals(jPasswordField_CapNhatThemBox_PassWord.getText())==false)
               {
                   error_String += "Xác Thực Mật Khẩu- ";
               }
               
       }
       if (error_String.equals("") == false) {
           JOptionPane.showMessageDialog(null, "Thông tin " + error_String + "không chính xác, vui lòng nhập lại!",
                   "Nhập sai thông tin", 2);
           return false;
       }
       return true;
   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuanLyTaiKhoan().setVisible(true);
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_CapNhatThemBox_CapNhat;
    private javax.swing.JButton btn_CapNhatThemBox_Them;
    private javax.swing.JButton btn_CapNhatThemBox_close;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_TimKiemBox_close;
    private javax.swing.JButton btn_TimKiemBox_search;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<String> jComboBox_CapNhatThemBox_Role;
    private javax.swing.JComboBox<String> jComboBox_TimKiemBox_item;
    private javax.swing.JFrame jFrame_CapNhatThem_dialog;
    private javax.swing.JFrame jFrame_TimKiem_dialog;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel_mainTittle;
    private javax.swing.JPanel jPanel_CapNhatThemBox;
    private javax.swing.JPanel jPanel_ChucNang_main;
    private javax.swing.JPanel jPanel_TimKiemBox;
    private javax.swing.JPasswordField jPasswordField_CapNhatThemBox_AgainPassWord;
    private javax.swing.JPasswordField jPasswordField_CapNhatThemBox_PassWord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_CapNhatThemBox_Username;
    private javax.swing.JTextField jTextField_TimKiemBox_searchString;
    // End of variables declaration//GEN-END:variables

    private Image Image(ImageIcon img_bookIcon) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
